### ISSUE TITLE
MySQL visualisations not showing up

### ISSUE THREAD

**Issue by yuvke** [EverythingMe/redash#379]
Hi @arikfr,

We're using the charts and dashboards frequently for our redshift DB and we now started adding some queries to our MySQL DB. The queries are returning correctly with data (we see it in the table tab), but when we try to create a chart from it - we're not seeing any visuals. The charts are working fine on the redshift queries. This seem to happen only on MySQL queries.

Any thoughts on what causes this?

**Comment by yuvke** [comment]
![screen shot 2015-03-01 at 5 54 54 pm](https://cloud.githubusercontent.com/assets/9798069/6431574/51d5bb62-c03c-11e4-8322-9315b4ca62be.png)
The result table

![screen shot 2015-03-01 at 5 55 35 pm](https://cloud.githubusercontent.com/assets/9798069/6431576/5f36041a-c03c-11e4-878d-aef08a710a23.png)
The chart definitions (part 1)

![screen shot 2015-03-01 at 5 55 43 pm](https://cloud.githubusercontent.com/assets/9798069/6431579/76c3952a-c03c-11e4-84f0-20467f96f1e7.png)
The chart definitions (part 2)

**Comment by arikfr** [comment]
The frontend isn't aware of the database type, so it shouldn't be related to MySQL.

And from the screenshots it all seems right, aside from not drawing the chart... how many rows the query returned? If you open Chrome's developer console (Cmd+Alt+J or Ctrl+Shift+J), do you see any errors there?

**Comment by yuvke** [comment]
A few errors:

![screen shot 2015-03-01 at 6 47 02 pm](https://cloud.githubusercontent.com/assets/9798069/6431752/767bf7f4-c043-11e4-81cb-14278dcd89bd.png)

**Comment by arikfr** [comment]
Highcharts error #14 is : "String value sent to series.data, expected Number".

Is it possible that Column D values returned as strings instead of numbers?

**Comment by yuvke** [comment]
Yup that was the case! Once we converted it to Deciimal the graph appeared. Thanks!

**Comment by arikfr** [comment]
Glad to know it's working. Closing issue now.
