### ISSUE TITLE
query refresh intervals 5m 10m 15m 30m

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [EverythingMe/redash#430]
It's a big jump from 1m to 1h. Can we have a few intervals in between?

**Comment by arikfr** [comment]
Sure. I'll add it tomorrow.

**Comment by eschultze** [comment]
That would be great! Thanks!

**Comment by arikfr** [comment]
It's in the 0.6.1 version: https://github.com/EverythingMe/redash/releases/tag/v0.6.1-rc
See upgrade instructions here: http://redash.io/deployment/upgrade.html

And of course, if you have any issues with the upgrade or questions, feel free to reach out.

**Comment by gabrielcrowdtilt** [comment]
Thanks, the first couple times I upgraded was done the wrong way, by hacking the bootstrap.sh. But now I know to just do:
  fab -H redash deploy_latest_release
