### ISSUE TITLE
When searching schemas by name you cannot see the columns

### ISSUE THREAD

**Issue by runa** [EverythingMe/redash#443]
1. choose any schema from the right list in "new query", click and you see the columns
2. now, write the schema name in the search box
3. try clicking on the schema name, the column names don't appear

**Comment by arikfr** [comment]
This is because it uses the same string to search in the table name and column names. But I got annoyed by it too, and going to keep the search for tables only.

**Comment by runa** [comment]
ahh. interesting

**Comment by arikfr** [comment]
![lmu5ynvqcq](https://cloud.githubusercontent.com/assets/71468/8009057/acd2f4d6-0bae-11e5-9729-8cdac1268529.gif)

Fixed, and I even kept the search in columns (see above). Will be available in the 0.6.1-RC release once build completes.
