### ISSUE TITLE
A question about database

### ISSUE THREAD

**Issue by tonychee7000** [EverythingMe/redash#452]
Hello,

I have a problem that when i use redash, table 'query_results' have taken too many disk space since 3 month ago, it's up to 17GB.

I've tried to delete some old data to release disk space, but failed with error about foreign keys.

So how can i clean the old data from database?

**Comment by tonychee7000** [comment]
i have found some way to clean the old data
just create a trigger

```sql
-- Create a function to clear the old data
CREATE OR REPLACE FUNCTION "Clean_Old_Data"()
  RETURNS trigger AS
$BODY$BEGIN
    DELETE FROM query_results WHERE id NOT IN (SELECT latest_query_data_id FROM queries);
    RETURN NEW;
END;$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

ALTER FUNCTION "Clean_Old_Data"()
  OWNER TO redash;

-- Then, create a trigger
CREATE TRIGGER "Clean_Old_Data"
  BEFORE INSERT
  ON query_results
  FOR EACH STATEMENT
  EXECUTE PROCEDURE "Clean_Old_Data"();

```

**Comment by arikfr** [comment]
If I'm not mistaken,  your solution will delete results of ad-hoc queries,
as they aren't attached to a query object and aren't referenced.

There is a built in clean up task that periodically removes old unused
results. It's *off* by default, as I wanted to test it first. But by now I
know it's OK.

Later today, when I'm at my computer, I'll send instructions on how to
enable it.

**Comment by arikfr** [comment]
@tonychee7000 to enable the built in cleanup, just add `REDASH_QUERY_RESULTS_CLEANUP_ENABLED=true` to your `.env` file (I'm assuming you've used one of the provided images to setup re:dash -- let me know if you need more elaborate instructions).

It deletes 100 query results on every iteration, so it might take some time to finish.

**Comment by kausikram** [comment]
can this task be force triggered ? as a manage.py command perhaps.

**Comment by arikfr** [comment]
> can this task be force triggered ? as a manage.py command perhaps.

```python

from redash.tasks import cleanup_query_results

clean_query_results()
```

Should be very simple to create a CLI command for it. Pull requests are welcomed :-)
