### ISSUE TITLE
CLI add new BigQuery datasource - Service Account is actually "Email" Service Account

### ISSUE THREAD

**Issue by WesleyBatista** [EverythingMe/redash#491]
Adding a new BigQuery datasource the CLI asks me about the service account:

![redash_cli_capture](https://cloud.githubusercontent.com/assets/755254/8698815/7603be02-2ad7-11e5-967e-610d5f32b766.png)

I typed the "Client ID", when actually we need to provide the "Email address"

**Comment by arikfr** [comment]
Thank you for pointing this out. Fixed it in #495.
