### ISSUE TITLE
Missing dependency on TCLIService

### ISSUE THREAD

**Issue by adrienkohlbecker** [EverythingMe/redash#533]
Hello,

I'm getting the following warning when launching redash:
```
[2015-08-19 12:49:45,978][PID:17][WARNING][redash.query_runner.hive_ds] Missing dependencies. Please install pyhive.
[2015-08-19 12:49:45,979][PID:17][WARNING][redash.query_runner.hive_ds] You can use pip: pip install pyhive
```

`pyhive` is installed, but looking at the redash code these seem to be due to the following `ImportError`
```
Python 2.7.10 (default, Jul 18 2015, 00:45:22)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhive import hive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyhive/hive.py", line 10, in <module>
    from TCLIService import TCLIService
ImportError: No module named TCLIService
```

Any idea of how I might solve it? I'm not familiar with hive

**Comment by alexanderlz** [comment]
Hi Adrien,

TCLIService is needed for the thrift protocol, to communicate with Hive server.
You should obtain it from Hive installation, or you can grab it from here https://github.com/alexanderlz/PyHive (in case u want a quick patch - just uninstall your PyHive module - and install the one provided in here)

**Comment by arikfr** [comment]
@adrienkohlbecker if you're not using re:dash with Hive, you can just ignore these messages. They are just warnings, for those who do want to use Hive.

I do realize it's confusing, and I'll change these messages (or remove them) in the future.

**Comment by arikfr** [comment]
Pleas reopen if still relevant.

**Comment by vbajaria** [comment]
@arikfr I just upgraded re:dash to the latest release and I still get this error. I wanted to try hive as a datasource, is this something that needs to be fixed for future versions ?

**Comment by arikfr** [comment]
Make sure you have the right version of pyhive (as defined in requirements_all_ds.txt).

**Comment by vbajaria** [comment]
Verified that pyhive is 0.1.6 in requirements_all_ds.txt but the installed version is 0.1.5

Not sure why this happened, maybe the fabric upgrade failed to refresh the packages ? Want me to look into this and add more info so that this can be fixed for future releases ?

**Comment by georgeliaw** [comment]
@arikfr we were able to resolve the versioning issue mentioned by @vbajaria 

Basically the problem was with python-pip on Ubuntu 14.04 being an old version with different behavior (`python-pip=1.5.4-1ubuntu4`), which prevented it from uninstalling pyhive (it was probably looking for `installed-files.txt` in the egg, which doesn't exist). After bumping pip to version 9.0.1, the issue went away.

What we saw when doing manual package install, which lead us to the conclusion that there was a pip issue:
```$ sudo pip install pyhive==0.1.6
Downloading/unpacking pyhive==0.1.6
  Downloading PyHive-0.1.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyhive/setup.py) egg_info for package pyhive
    
Installing collected packages: pyhive
  Found existing installation: PyHive 0.1.5
    Can't uninstall 'PyHive'. No files were found to uninstall.
  Running setup.py install for pyhive
    
  Could not find .egg-info directory in install record for pyhive==0.1.6
Successfully installed pyhive
Cleaning up...```

**Comment by arikfr** [comment]
@georgeliaw thanks for the follow up and writeup. 👍
