### ISSUE TITLE
Floats are truncated to 2 decimal points

### ISSUE THREAD

**Issue by shayel** [EverythingMe/redash#536]
The [gridRednerer forces floats to 2 decimal points](https://github.com/EverythingMe/redash/blob/master/rd_ui/app/scripts/visualizations/table.js#L71), and I couldn't find a way to configure this.

Is there an settings I am missing?

If not, would you accept a patch adding formatting/visualization options to a table, similar to the way a chart visualization is configures?

**Comment by arikfr** [comment]
You're not missing anything, it's indeed impossible. And not only I'll
accept such a patch, it will be much appreciated.

I was thinking of a popup (modal) with configuration per column setting its
type, and relevant options for this type. You can see an example of opening
a modal here:
https://github.com/EverythingMe/redash/blob/master/rd_ui/app/scripts/controllers/query_view.js#L219

**Comment by matiascarazzo** [comment]
Arik, that could be a really good way to add any customization, on format
and even links on the columns.

Regards
Matias


Matias Carazzo
Tech Lead
*DevSpark <http://www.devspark.com/>*
*Skype *matias.carazzo
