### ISSUE TITLE
Cannot delete dashboard from home page

### ISSUE THREAD

**Issue by jhammer** [EverythingMe/redash#541]
On the home page, clicking the "X" next to a dashboard brings up the "are you sure" alert, but clicking OK results in the dashboard not being deleted. The title disappears, but if you reload the page the dashboard is still there.

Version 0.7.1+b1015

**Comment by arikfr** [comment]
It's a bug in the new code that generates the recent dashboards list, it doesn't filter out the archived dashboards. I got aware of it shortly before going on vacation, and I'll fix it when I'm back. Sorry about the confusion.

Once this is fixed, all the dashboards you archived (deleted) will be removed from the list on the homepage.

**Comment by arikfr** [comment]
Fixed it in #544 and it's part of the 0.7.1-RC release. I'll "close" the version on Sunday and have a proper release then.
