### ISSUE TITLE
fabfile doesn't work with latest unstable release

### ISSUE THREAD

**Issue by stanhu** [EverythingMe/redash#561]
I tried to deploy the RC via:

```
fab deploy_latest_release:stable=false
```

But it appears the `assets` array is empty via https://api.github.com/repos/EverythingMe/redash/releases.

![image](https://cloud.githubusercontent.com/assets/963826/9948392/7cddb59a-5d57-11e5-8be7-995e666130a3.png)

**Comment by arikfr** [comment]
There is some problem with the script that uploads the build artifact. I've attached it manually now, until I get it resolved.

**Comment by arikfr** [comment]
Fixed by 5f656f38683c0c7c755818cf2a08662cab25ea43.
