### ISSUE TITLE
API keys should be supported in the HTTP headers

### ISSUE THREAD

**Issue by stanhu** [EverythingMe/redash#564]
Currently it seems that all API calls must include the `api_key` in the query string. Ideally the HTTP headers could also be used (e.g. `Authorization: Key XXXX` or `X-Api-Key`) so that Web server logs don't log the API key in the clear.

**Comment by arikfr** [comment]
Good idea, it just a matter of updating this function:
https://github.com/EverythingMe/redash/blob/master/redash/authentication.py#L71 to read the value from query string or headers.

**Comment by toyama-h** [comment]
+1
