### ISSUE TITLE
Row count limitation when creating chart visualization

### ISSUE THREAD

**Issue by grantatsyncbak** [EverythingMe/redash#572]
Graphing query with series data works fine when there are 1150 rows returned (total) but not when I go back further in time and get 1543 rows.  The chart shows just one of the two data points used as series.  The error in the console shows: "Highcharts error #12: www.highcharts.com/errors/12", and the link refers to the turboThreshold.  I did not see any references to this when searching through the code.

**Comment by arikfr** [comment]
It's a HighCharts limitation. They have two suggested solutions (mentioned on the linked error page), but I never had the chance to explore this in detail.

You can try to disable the `turboThreshold` value to disable the limitation or just change it to higher value (2000? 5000?).

There is an "advanced" undocumented option of editing the JSON parameters passed to HighCharts. If you're interested, I can explain how to enable it.

**Comment by grantatsyncbak** [comment]
Thanks!  Would you be able to give some guidance where I would change the turboThreshold value?  Or is the only way to do this through the undocumented option you mention above?

**Comment by arikfr** [comment]
Currently it's only possible through the undocumented option. It will require shell access to the re:dash server, to add the required permission to your user.

As an alternative, I can add tomorrow the `turboThreshold` as a configuration parameter to re:dash. It will require you to upgrade once I do that. http://docs.redash.io/en/latest/upgrade.html
