### ISSUE TITLE
"execute_query" permission doesn't work

### ISSUE THREAD

**Issue by mitomemel** [EverythingMe/redash#581]
I created a new group that doesn't have the permission "execute_query", but "Execute" button and "Refresh Dataset" button are displayed yet.

**Comment by arikfr** [comment]
You're correct - looks like the UI doesn't "respect" the permission, but the backend does. Do you get an error when trying to press one of those buttons?

**Comment by mitomemel** [comment]
Yes. I pressed the button, but the query hasn't completed.
