### ISSUE TITLE
Can't show any datasource types

### ISSUE THREAD

**Issue by jeff1026j** [EverythingMe/redash#592]
I just setup reddish to a new machine, then I want to add new datasource, I can't see any DB Types below ??  I'm sure I install all the dependencies, and I find out a 403 forbidden to 

http://[mywebsite]/api/data_sources/types

is that related to my problem ??

thx

**Comment by arikfr** [comment]
Are you logging in with a user that has admin privileges?

**Comment by jeff1026j** [comment]
omg, that's true, does anyone know how to change the admin password or grant admin permission to google accounts ?

I can't find where's this one :
/users/me#password

**Comment by arikfr** [comment]
You can use the cli for that:

From your re:dash folder (/opt/redash/current if you used the bootstrap
script):
bin/run ./manage.py grant_admin {email}

To grant admin privileges to a new user.

To change admin password:
bin/run ./manage.py password admin new_password

Note that the default admin password is admin.

Also if you used the bootstrap script you might need to prefix the commands
with "sudo -u redash", i.e.: "sudo -u redash bin/run ./manage.py ...".

**Comment by jeff1026j** [comment]
really thx for your help!

ok, I know the problem, I saw the docs from here http://docs.redash.io and the default version is latest, and the latest version of docs doesn't have these infos....

and now I have another problem...  
I use admin to login, now I can add datasource, but I can't delete the existing dashboard ??

**Comment by arikfr** [comment]
That's strange. You don't have a red archive button on the dashboard page?

**Comment by jeff1026j** [comment]
here's my home page looks like 

![screen shot 2015-10-09 at 3 03 20 pm](https://cloud.githubusercontent.com/assets/1669417/10387827/3490c204-6e97-11e5-9f0b-d128a566147b.png)

**Comment by jeff1026j** [comment]
ad the dashboard page (also login as admin)

![screen shot 2015-10-09 at 3 10 33 pm](https://cloud.githubusercontent.com/assets/1669417/10387926/f9f12df4-6e97-11e5-9123-075c609de086.png)

**Comment by arikfr** [comment]
I assumed you clicked on the grey "X" on the homepage, and they still appear there , right?

It's a bug we had in the version you're using. If you upgrade, it will be fixed (and the dashboards deleted will be gone). http://docs.redash.io/en/latest/upgrade.html

**Comment by arikfr** [comment]
@jeff1026j please reopen if it's still not working after upgrade.

**Comment by jeff1026j** [comment]
I just try it and it success!!  thx
