### ISSUE TITLE
Document how to add python datasource?

### ISSUE THREAD

**Issue by tjwudi** [EverythingMe/redash#595]
According to [docs](http://docs.redash.io/en/latest/datasources.html#python), python datasources are allowed. But I cannot see python option when setting up new datasource. Is there anything need to be configured but not yet documented?

![screen shot 2015-10-08 at 3 35 04 pm](https://cloud.githubusercontent.com/assets/5257816/10381758/30512136-6dd2-11e5-928f-2dc6327f0761.png)

**Comment by Oneross** [comment]
In settings.py, lines 115-131define enabled query runners.  Recommend either adding redash.query_runner.python to QUERY_RUNNERS in settings.py or defining it in REDASH_ENABLED_QUERY_RUNNERS environment variable before launch.

https://github.com/EverythingMe/redash/blob/master/redash/settings.py#L115-L131

**Comment by tjwudi** [comment]
@Oneross Was it ignored on purpose or it's a bug? If it is a bug, I can submit a PR with `redash.query_runner.python` added; If it is not, I will document it instead.

**Comment by Oneross** [comment]
I'm new to the community, I have a pull request ready for documentation (just a notes section) - my take is that since security of the sandboxed runner isn't 100% it's off by default.

**Comment by tjwudi** [comment]
@Oneross Cool. Could you please comment or reference this issue once your PR is merged?

**Comment by tjwudi** [comment]
@Oneross Oh hey I see the PR. Thanks for that :) I am going to close this issue.

**Comment by arikfr** [comment]
@oneross is correct. It's off by default to avoid users enabling it without fully understanding what they're doing. 

Btw, I'm not a hacker but I managed to bypass the sandbox given a library like requests is whitewashed.

**Comment by tjwudi** [comment]
It is somehow confusing to have three way to enable/disable a query runner, isn't it?

- By returning `False` in `enabled()` class method of the query runner
- By changing **settings.py**
- By setting environment variables

**Comment by arikfr** [comment]
The enabled() method makes sure that the query runner can be actually used (I.e. It has all dependencies). And it's a safe guard against people enabling query runners without installing the needed packages. 

Setting the env variable is a way to control what data sources you want to support in your redash instance.  

Changing settings.py isn't recommended as this is what the Env vars are for. 

Coming to think of it, we can change enabled() into a runtime error, that you will get when trying to run a query. Might make things clearer.

**Comment by Oneross** [comment]
@arikfr , I updated the pull req to reflect preference against changing settings.py.
