### ISSUE TITLE
sqlite support

### ISSUE THREAD

**Issue by gissehel** [EverythingMe/redash#627]
Is support for sqlite databases something feasible ?

**Comment by spectr** [comment]
+1

**Comment by gissehel** [comment]
I've checked the code, it should not be much to do, I'll try to contribute that change.

**Comment by arikfr** [comment]
:+1: indeed it should be simple enough, and similar to the MySQL or Postgres query runners.

But I'm curious: in what use case you find it useful to connect re:dash to a sqlite datasource?

**Comment by gissehel** [comment]
I've submitted a pull request with that feature.

For those who want to test it easily, I've pushed a docker image gissehel/docker_sqlite that contains:
- master
- the docker branch
- the init_database branch I've sumitted ( #629 )  to easily create a new database with the image
- this sqlite_query_runner branch I've sumitted ( #630 ) for sqlite support.

**Comment by gissehel** [comment]
>  in what use case you find it useful to connect re:dash to a sqlite datasource?

When... I need to easily get & graph informations out of a sqlite datasource :)

I wrote a tool that analyze several log sources from a production environment, and daily consolidate those informations in a sqlite database, and then extract graphs from those tables. Those tables are a mine of informations that are useful for those who can query them.

Plugging re:dash on that database would allow to easily extract information from that database, remeber useful queries under names, and perhaps let my boss and co-worker be aware of those informations with pretty graph without letting them drawn into Sqlite queries.

**Comment by spectr** [comment]
Our app, which is installed at customer sites, uses sqlite to store data and logs. We retrieve sqlite DBs on a daily basis for troubleshooting purposes. Would be nice to visualize data and store common queries.
