### ISSUE TITLE
No way to delete unneeded queries

### ISSUE THREAD

**Issue by yosefw** [EverythingMe/redash#64]
#### Problems
Unneeded (duplicate, of low quality etc.) can quickly clutter the queries list.

#### Solution
An "archive" feature, allowing users to archive a query, effectively removing it from the “live” re:dash content, but allowing them to restore it.

**Comment by arikfr** [comment]
Implemented in #358; included in: https://github.com/EverythingMe/redash/releases/tag/v0.5.0%2Bb648

FYI: @gabrielcrowdtilt @clevinson

Note that migration is needed.
